name: local_dea_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  bloc: ^8.0.3
  carousel_slider: ^4.0.0
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bcrypt: ^1.0.7
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.3
  intl: ^0.17.0
  location: ^4.3.0
  mask_text_input_formatter: ^2.1.0
  page_transition: ^2.0.5
  tuple: ^2.0.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/dea_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/dea_icon.png
    - assets/dea_icon_marker.png
    - assets/edificio-hospitalar.png
    - assets/samu_icon.png
    - assets/step1.png
    - assets/step2.png
    - assets/step3.png
    - assets/step4.png
